// Auto-generated by scripts/rv32i_asm.py -- do not hand-edit.
`timescale 1ns/1ps

module rv32i_soc_imem (
    input  logic [31:0] addr_i,
    output logic [31:0] rdata_o
);

    /* verilator lint_off UNUSEDSIGNAL */
    logic _unused_addr;
    assign _unused_addr = ^addr_i;  // only addr_i[8:2] indexes the ROM below
    /* verilator lint_on UNUSEDSIGNAL */

    // Icarus rejects a part-select used directly as a case expression
    // ("constant selects in always_* processes are not currently
    // supported") -- an explicit intermediate wire avoids it, same fix
    // as imem_stub.sv's/rv32i_lsu.sv's rom_idx/addr_byte_sel.
    wire [6:0] rom_idx = addr_i[8:2];

    always_comb begin
        unique case (rom_idx)
            0: rdata_o = 32'h000022B7;
            1: rdata_o = 32'h00028293;
            2: rdata_o = 32'h3F800337;
            3: rdata_o = 32'h00030313;
            4: rdata_o = 32'h0062A223;
            5: rdata_o = 32'h0062A423;
            6: rdata_o = 32'h0002A623;
            7: rdata_o = 32'h0002A823;
            8: rdata_o = 32'h00000393;
            9: rdata_o = 32'h0072A023;
            10: rdata_o = 32'h01C2A403;
            11: rdata_o = 32'h00147493;
            12: rdata_o = 32'hFE048CE3;
            13: rdata_o = 32'h01C2A403;
            14: rdata_o = 32'h00247493;
            15: rdata_o = 32'hFE048CE3;
            16: rdata_o = 32'h0142A503;
            17: rdata_o = 32'h00000593;
            18: rdata_o = 32'h00A5A023;
            19: rdata_o = 32'h0005A603;
            20: rdata_o = 32'h000016B7;
            21: rdata_o = 32'h00068693;
            22: rdata_o = 32'h0086A703;
            23: rdata_o = 32'h00177793;
            24: rdata_o = 32'hFE078CE3;
            25: rdata_o = 32'h04100813;
            26: rdata_o = 32'h0106A023;
            27: rdata_o = 32'h0086A703;
            28: rdata_o = 32'h00277793;
            29: rdata_o = 32'hFE078CE3;
            30: rdata_o = 32'h0046A883;
            31: rdata_o = 32'h0115A423;
            32: rdata_o = 32'h00100913;
            33: rdata_o = 32'h0126A623;
            34: rdata_o = 32'h00003BB7;
            35: rdata_o = 32'h000B8B93;
            36: rdata_o = 32'h00400C13;
            37: rdata_o = 32'h018BA023;
            38: rdata_o = 32'h00500C93;
            39: rdata_o = 32'h019BA423;
            40: rdata_o = 32'h50000C93;
            41: rdata_o = 32'h019BA623;
            42: rdata_o = 32'h00050CB7;
            43: rdata_o = 32'h000C8C93;
            44: rdata_o = 32'h019BA823;
            45: rdata_o = 32'h05000CB7;
            46: rdata_o = 32'h000C8C93;
            47: rdata_o = 32'h019BAA23;
            48: rdata_o = 32'h00500C13;
            49: rdata_o = 32'h018BA023;
            50: rdata_o = 32'h004BAD03;
            51: rdata_o = 32'h001D7D93;
            52: rdata_o = 32'hFE0D8CE3;
            53: rdata_o = 32'h00600C13;
            54: rdata_o = 32'h018BA023;
            55: rdata_o = 32'h04030E37;
            56: rdata_o = 32'h201E0E13;
            57: rdata_o = 32'h01CBAC23;
            58: rdata_o = 32'h004BAD03;
            59: rdata_o = 32'h004D7D93;
            60: rdata_o = 32'hFE0D8CE3;
            61: rdata_o = 32'h01CBAE83;
            62: rdata_o = 32'h01D5A623;
            63: rdata_o = 32'h00C00C13;
            64: rdata_o = 32'h018BA023;
            65: rdata_o = 32'h00600C13;
            66: rdata_o = 32'h018BA023;
            67: rdata_o = 32'h09080F37;
            68: rdata_o = 32'h706F0F13;
            69: rdata_o = 32'h01EBAC23;
            70: rdata_o = 32'h004BAD03;
            71: rdata_o = 32'h004D7D93;
            72: rdata_o = 32'hFE0D8CE3;
            73: rdata_o = 32'h01CBAF83;
            74: rdata_o = 32'h01F5A823;
            75: rdata_o = 32'h000049B7;
            76: rdata_o = 32'h00098993;
            77: rdata_o = 32'h0000EA37;
            78: rdata_o = 32'hEADA0A13;
            79: rdata_o = 32'h0149A023;
            80: rdata_o = 32'h0009AA83;
            81: rdata_o = 32'hCAFEFB37;
            82: rdata_o = 32'h00DB0B13;
            83: rdata_o = 32'h0165A223;
            84: rdata_o = 32'h0000006F;
            default: rdata_o = 32'h00000013;  // NOP past the program end
        endcase
    end

endmodule
