// Auto-generated by scripts/rv32i_asm.py -- do not hand-edit.
`timescale 1ns/1ps

module rv32i_soc_imem (
    input  logic [31:0] addr_i,
    output logic [31:0] rdata_o
);

    /* verilator lint_off UNUSEDSIGNAL */
    logic _unused_addr;
    assign _unused_addr = ^addr_i;  // only addr_i[7:2] indexes the ROM below
    /* verilator lint_on UNUSEDSIGNAL */

    // Icarus rejects a part-select used directly as a case expression
    // ("constant selects in always_* processes are not currently
    // supported") -- an explicit intermediate wire avoids it, same fix
    // as imem_stub.sv's/rv32i_lsu.sv's rom_idx/addr_byte_sel.
    wire [5:0] rom_idx = addr_i[7:2];

    always_comb begin
        unique case (rom_idx)
            0: rdata_o = 32'h000022B7;
            1: rdata_o = 32'h00028293;
            2: rdata_o = 32'h3F800337;
            3: rdata_o = 32'h00030313;
            4: rdata_o = 32'h0062A223;
            5: rdata_o = 32'h0062A423;
            6: rdata_o = 32'h0002A623;
            7: rdata_o = 32'h0002A823;
            8: rdata_o = 32'h00000393;
            9: rdata_o = 32'h0072A023;
            10: rdata_o = 32'h01C2A403;
            11: rdata_o = 32'h00147493;
            12: rdata_o = 32'hFE048CE3;
            13: rdata_o = 32'h01C2A403;
            14: rdata_o = 32'h00247493;
            15: rdata_o = 32'hFE048CE3;
            16: rdata_o = 32'h0142A503;
            17: rdata_o = 32'h00000593;
            18: rdata_o = 32'h00A5A023;
            19: rdata_o = 32'h0005A603;
            20: rdata_o = 32'h000016B7;
            21: rdata_o = 32'h00068693;
            22: rdata_o = 32'h0086A703;
            23: rdata_o = 32'h00177793;
            24: rdata_o = 32'hFE078CE3;
            25: rdata_o = 32'h04100813;
            26: rdata_o = 32'h0106A023;
            27: rdata_o = 32'h0086A703;
            28: rdata_o = 32'h00277793;
            29: rdata_o = 32'hFE078CE3;
            30: rdata_o = 32'h0046A883;
            31: rdata_o = 32'h0115A423;
            32: rdata_o = 32'h00100913;
            33: rdata_o = 32'h0126A623;
            34: rdata_o = 32'h000039B7;
            35: rdata_o = 32'h00098993;
            36: rdata_o = 32'h0000EA37;
            37: rdata_o = 32'hEADA0A13;
            38: rdata_o = 32'h0149A023;
            39: rdata_o = 32'h0009AA83;
            40: rdata_o = 32'hCAFEFB37;
            41: rdata_o = 32'h00DB0B13;
            42: rdata_o = 32'h0165A223;
            43: rdata_o = 32'h0000006F;
            default: rdata_o = 32'h00000013;  // NOP past the program end
        endcase
    end

endmodule
