// imem_stub.sv — combinational case-statement instruction ROM for
// rv32i_core's standalone testbenches. NOT part of the IP's own rtl/ (the
// real ROM is composed in rv32i_soc later, per this build's plan) — this
// stub only exists so rv32i_core can be exercised on its own.
//
// Case body is auto-generated by gen_test_program.py from a labeled
// instruction list (two-pass encoder — branch/jump offsets are computed,
// never hand-derived, after this same build already caught one real
// hand-encoding bug at the single-instruction scale). Regenerate with:
//   python3 gen_test_program.py > /tmp/rom_body.txt
// and paste the case block back in below if the program ever changes.
`timescale 1ns/1ps

module imem_stub (
    input  logic [31:0] addr_i,
    output logic [31:0] rdata_o
);

    /* verilator lint_off UNUSEDSIGNAL */
    logic _unused_addr;
    assign _unused_addr = ^addr_i;  // only addr_i[8:2] indexes the ROM below
    /* verilator lint_on UNUSEDSIGNAL */

    // Icarus rejects a part-select used directly as a case expression
    // ("constant selects in always_* processes are not currently
    // supported (all bits will be included)") -- an explicit
    // intermediate wire avoids it, same fix as rv32i_ctrl_decode.sv's
    // branch_cmp_grp / rv32i_lsu.sv's addr_byte_sel.
    wire [6:0] rom_idx = addr_i[8:2];

    always_comb begin
        // Auto-generated by gen_test_program.py -- do not hand-edit.
        unique case (rom_idx)
            0: rdata_o = 32'h00000093;
            1: rdata_o = 32'h00500113;
            2: rdata_o = 32'h00700193;
            3: rdata_o = 32'h00310233;
            4: rdata_o = 32'h402202B3;
            5: rdata_o = 32'h00317333;
            6: rdata_o = 32'h003163B3;
            7: rdata_o = 32'h00314433;
            8: rdata_o = 32'h00111493;
            9: rdata_o = 32'h00225513;
            10: rdata_o = 32'hFF800593;
            11: rdata_o = 32'h4015D613;
            12: rdata_o = 32'h003126B3;
            13: rdata_o = 32'h0021B733;
            14: rdata_o = 32'h00A12793;
            15: rdata_o = 32'h0031F813;
            16: rdata_o = 32'h00816893;
            17: rdata_o = 32'h0011C913;
            18: rdata_o = 32'h123459B7;
            19: rdata_o = 32'h00000A17;
            20: rdata_o = 32'h0040A023;
            21: rdata_o = 32'h0090A223;
            22: rdata_o = 32'h00609423;
            23: rdata_o = 32'h00808623;
            24: rdata_o = 32'h0330A023;
            25: rdata_o = 32'h0340A223;
            26: rdata_o = 32'h0000AA83;
            27: rdata_o = 32'h015A8B33;
            28: rdata_o = 32'h0160A823;
            29: rdata_o = 32'h00210463;
            30: rdata_o = 32'h7FF00B93;
            31: rdata_o = 32'h00000013;
            32: rdata_o = 32'h00311463;
            33: rdata_o = 32'h7FE00B93;
            34: rdata_o = 32'h00000013;
            35: rdata_o = 32'h00314463;
            36: rdata_o = 32'h7FD00B93;
            37: rdata_o = 32'h00000013;
            38: rdata_o = 32'h0021D463;
            39: rdata_o = 32'h7FC00B93;
            40: rdata_o = 32'h00000013;
            41: rdata_o = 32'h00316463;
            42: rdata_o = 32'h7FB00B93;
            43: rdata_o = 32'h00000013;
            44: rdata_o = 32'h0021F463;
            45: rdata_o = 32'h7FA00B93;
            46: rdata_o = 32'h00000013;
            47: rdata_o = 32'h06300B93;
            48: rdata_o = 32'h0170AA23;
            49: rdata_o = 32'h00800CEF;
            50: rdata_o = 32'h0000AC23;
            51: rdata_o = 32'h00000013;
            52: rdata_o = 32'h0190AC23;
            53: rdata_o = 32'h00000D17;
            54: rdata_o = 32'h010D0D13;
            55: rdata_o = 32'h000D0DE7;
            56: rdata_o = 32'h0000AE23;
            57: rdata_o = 32'h00000013;
            58: rdata_o = 32'h01B0AE23;
            59: rdata_o = 32'h00100F93;
            60: rdata_o = 32'h07F0A223;
            61: rdata_o = 32'h00000013;
            62: rdata_o = 32'h00000013;
            63: rdata_o = 32'h00000013;
            64: rdata_o = 32'h00000013;
            default: rdata_o = 32'h00000013;  // NOP past the program end
        endcase
    end

endmodule
